version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Setup Ubuntu 18.04 on WSL"
          shell: powershell.exe -Verb RunAs
          no_output_timeout: 30m
          command: |
            Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
            Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx -UseBasicParsing
            Rename-Item .\Ubuntu.appx .\Ubuntu.zip
            Expand-Archive .\Ubuntu.zip .\Ubuntu
            cd .\Ubuntu\
            .\ubuntu1804.exe install --root
            .\ubuntu1804.exe
            git clone https://github.com/pytorch/serve.git
            cd serve
            echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc
            source ~/.bashrc
            ./torchserve_sanity.sh
